// Skill data — structured for easy API replacement later
const CATEGORIES = [
  { id: "all", label: "All Skills", icon: "grid", bg: "#EEF2FF", fg: "#4F46E5" },
  { id: "qa", label: "QA & Testing", icon: "bug", bg: "#EFF6FF", fg: "#2563EB" },
  { id: "frontend", label: "Frontend", icon: "monitor", bg: "#FFF7ED", fg: "#EA580C" },
  { id: "backend", label: "Backend", icon: "server", bg: "#ECFDF5", fg: "#16A34A" },
  { id: "database", label: "Database", icon: "database", bg: "#EEF2FF", fg: "#4F46E5" },
  { id: "devops", label: "DevOps & Cloud", icon: "cloud", bg: "#F0F9FF", fg: "#0284C7" },
  { id: "mobile", label: "Mobile Dev", icon: "smartphone", bg: "#F5F3FF", fg: "#7C3AED" },
  { id: "data", label: "Data & Analytics", icon: "bar-chart", bg: "#FFFBEB", fg: "#D97706" },
  { id: "ai", label: "AI & Machine Learning", icon: "brain", bg: "#FDF2F8", fg: "#DB2777" },
  { id: "design", label: "UI/UX Design", icon: "pen-tool", bg: "#FFF1F2", fg: "#E11D48" },
  { id: "pm", label: "Project & Agile", icon: "kanban", bg: "#F0FDFA", fg: "#0D9488" },
];

// Pre-built glyph/logo per skill — a colored square with monogram or simple mark
// Each entry: { name, cat, desc, level, verified, candidates, jobs, glyph: {bg, fg, label}, topics?, related? }
const SKILLS = [
  // QA & Testing
  { name: "Manual Testing", cat: "qa", desc: "Exploratory and structured manual test execution.", level: "Beginner", verified: true, candidates: 1820, jobs: 142, glyph: { bg: "#0f172a", fg: "#fff", label: "MT" } },
  { name: "Functional Testing", cat: "qa", desc: "Validate features against business requirements.", level: "Intermediate", verified: true, candidates: 1450, jobs: 121, glyph: { bg: "#1e293b", fg: "#fff", label: "FT" } },
  { name: "Regression Testing", cat: "qa", desc: "Re-run tests to catch defects from changes.", level: "Intermediate", verified: true, candidates: 1188, jobs: 96, glyph: { bg: "#334155", fg: "#fff", label: "RT" } },
  { name: "Automation Testing", cat: "qa", desc: "Automate test execution with scripts and tools.", level: "Advanced", verified: true, candidates: 1670, jobs: 178, glyph: { bg: "#16a34a", fg: "#fff", label: "AT" } },
  {
    name: "Selenium WebDriver", cat: "qa",
    desc: "Automate web application testing across browsers.",
    level: "Intermediate", verified: true, candidates: 245, jobs: 38,
    glyph: { bg: "#43B02A", fg: "#fff", label: "Se" },
    longDesc: "Automate web application testing across browsers using Selenium WebDriver.",
    topics: ["Locators", "WebDriver commands", "Waits", "TestNG", "Page Object Model", "Cross-browser testing", "Framework design", "Selenium Grid", "Headless execution", "Action class", "Screenshots & reporting", "Maven/Gradle integration"],
    related: ["Java", "TestNG", "Cucumber", "Jenkins", "API Testing"],
    activeJobsList: [
      { title: "QA Automation Engineer", company: "Tech Mahindra", location: "Remote" },
      { title: "Selenium Test Engineer", company: "Infosys", location: "Bangalore" },
      { title: "Test Automation Engineer", company: "TCS", location: "Hyderabad" },
    ],
  },
  { name: "Playwright", cat: "qa", desc: "Modern end-to-end testing for the modern web.", level: "Intermediate", verified: true, candidates: 412, jobs: 56, glyph: { bg: "#2EAD33", fg: "#fff", label: "Pw" } },
  { name: "Cypress", cat: "qa", desc: "Fast, reliable, all-in-one testing framework.", level: "Intermediate", verified: true, candidates: 530, jobs: 64, glyph: { bg: "#17202C", fg: "#fff", label: "Cy" } },
  { name: "Appium", cat: "qa", desc: "Open-source mobile app automation framework.", level: "Advanced", verified: true, candidates: 198, jobs: 24, glyph: { bg: "#662D91", fg: "#fff", label: "Ap" } },
  { name: "API Testing", cat: "qa", desc: "Validate REST and GraphQL endpoints.", level: "Intermediate", verified: true, candidates: 1240, jobs: 187, glyph: { bg: "#0ea5e9", fg: "#fff", label: "AP" } },
  { name: "Postman", cat: "qa", desc: "Build, test, and document APIs visually.", level: "Beginner", verified: true, candidates: 1675, jobs: 142, glyph: { bg: "#FF6C37", fg: "#fff", label: "Po" } },
  { name: "Rest Assured", cat: "qa", desc: "Java DSL for testing REST services.", level: "Intermediate", verified: true, candidates: 312, jobs: 41, glyph: { bg: "#6DB33F", fg: "#fff", label: "RA" } },
  { name: "JMeter", cat: "qa", desc: "Load and performance testing for web apps.", level: "Intermediate", verified: true, candidates: 426, jobs: 52, glyph: { bg: "#D22128", fg: "#fff", label: "JM" } },
  { name: "TestNG", cat: "qa", desc: "Powerful Java testing framework.", level: "Intermediate", verified: true, candidates: 384, jobs: 47, glyph: { bg: "#E32C2D", fg: "#fff", label: "TN" } },
  { name: "Cucumber BDD", cat: "qa", desc: "Behaviour-driven development with Gherkin.", level: "Intermediate", verified: true, candidates: 268, jobs: 33, glyph: { bg: "#23A455", fg: "#fff", label: "Cu" } },
  { name: "Mobile Testing", cat: "qa", desc: "Validate iOS and Android app quality.", level: "Intermediate", verified: true, candidates: 612, jobs: 78, glyph: { bg: "#0f172a", fg: "#fff", label: "Mo" } },
  { name: "Cross Browser Testing", cat: "qa", desc: "Ensure UX parity across browsers.", level: "Beginner", verified: true, candidates: 540, jobs: 41, glyph: { bg: "#0284c7", fg: "#fff", label: "CB" } },
  { name: "Performance Testing", cat: "qa", desc: "Measure throughput, latency, and stability.", level: "Advanced", verified: true, candidates: 420, jobs: 67, glyph: { bg: "#dc2626", fg: "#fff", label: "PT" } },
  { name: "Security Testing", cat: "qa", desc: "Find vulnerabilities before attackers do.", level: "Advanced", verified: false, candidates: 156, jobs: 84, glyph: { bg: "#111827", fg: "#fff", label: "ST" } },
  { name: "Accessibility Testing", cat: "qa", desc: "WCAG-compliant, inclusive product testing.", level: "Intermediate", verified: true, candidates: 232, jobs: 31, glyph: { bg: "#7c3aed", fg: "#fff", label: "A11y" } },
  { name: "SQL Testing", cat: "qa", desc: "Verify data integrity with SQL queries.", level: "Intermediate", verified: true, candidates: 478, jobs: 56, glyph: { bg: "#0369a1", fg: "#fff", label: "SQ" } },
  { name: "Jira", cat: "qa", desc: "Track tickets, sprints, and defects.", level: "Beginner", verified: true, candidates: 2100, jobs: 198, glyph: { bg: "#0052CC", fg: "#fff", label: "Ji" } },

  // Frontend
  { name: "HTML", cat: "frontend", desc: "Semantic markup for the modern web.", level: "Beginner", verified: true, candidates: 3200, jobs: 412, glyph: { bg: "#E34F26", fg: "#fff", label: "<>" } },
  { name: "CSS", cat: "frontend", desc: "Styling, layout, and responsive design.", level: "Beginner", verified: true, candidates: 3050, jobs: 398, glyph: { bg: "#1572B6", fg: "#fff", label: "#" } },
  {
    name: "JavaScript", cat: "frontend",
    desc: "Programming language for building interactive web apps.",
    level: "Intermediate", verified: true, candidates: 1200, jobs: 124,
    glyph: { bg: "#F7DF1E", fg: "#000", label: "JS" },
    topics: ["Variables & types", "Functions & closures", "Promises & async/await", "DOM manipulation", "ES6+ features", "Modules", "Event loop", "Error handling"],
    related: ["TypeScript", "React.js", "Node.js", "HTML", "CSS"],
  },
  { name: "TypeScript", cat: "frontend", desc: "Typed superset of JavaScript at scale.", level: "Intermediate", verified: true, candidates: 980, jobs: 167, glyph: { bg: "#3178C6", fg: "#fff", label: "TS" } },
  { name: "React.js", cat: "frontend", desc: "Component-based UI library by Meta.", level: "Intermediate", verified: true, candidates: 1500, jobs: 158, glyph: { bg: "#0f172a", fg: "#61DAFB", label: "⚛" } },
  { name: "Next.js", cat: "frontend", desc: "Production React framework with SSR.", level: "Advanced", verified: true, candidates: 642, jobs: 98, glyph: { bg: "#000000", fg: "#fff", label: "N" } },
  { name: "Angular", cat: "frontend", desc: "Full-featured TypeScript SPA framework.", level: "Advanced", verified: true, candidates: 720, jobs: 102, glyph: { bg: "#DD0031", fg: "#fff", label: "Ng" } },
  { name: "Vue.js", cat: "frontend", desc: "Approachable, performant SPA framework.", level: "Intermediate", verified: true, candidates: 487, jobs: 64, glyph: { bg: "#41B883", fg: "#fff", label: "Vu" } },
  { name: "Tailwind CSS", cat: "frontend", desc: "Utility-first CSS framework.", level: "Beginner", verified: true, candidates: 884, jobs: 124, glyph: { bg: "#06B6D4", fg: "#fff", label: "tw" } },
  { name: "Bootstrap", cat: "frontend", desc: "Popular CSS toolkit for fast UIs.", level: "Beginner", verified: true, candidates: 1320, jobs: 96, glyph: { bg: "#7952B3", fg: "#fff", label: "B" } },
  { name: "Redux", cat: "frontend", desc: "Predictable state container for JS apps.", level: "Intermediate", verified: true, candidates: 540, jobs: 78, glyph: { bg: "#764ABC", fg: "#fff", label: "Rx" } },
  { name: "Responsive Web Design", cat: "frontend", desc: "Layouts that adapt to any screen size.", level: "Beginner", verified: true, candidates: 1670, jobs: 132, glyph: { bg: "#0ea5e9", fg: "#fff", label: "RW" } },
  { name: "Web Accessibility", cat: "frontend", desc: "Build interfaces everyone can use.", level: "Intermediate", verified: false, candidates: 218, jobs: 41, glyph: { bg: "#7c3aed", fg: "#fff", label: "WA" } },

  // Backend
  { name: "Node.js", cat: "backend", desc: "JavaScript runtime for building scalable server-side apps.", level: "Intermediate", verified: true, candidates: 892, jobs: 96, glyph: { bg: "#339933", fg: "#fff", label: "JS" } },
  { name: "Express.js", cat: "backend", desc: "Minimal Node.js web framework.", level: "Intermediate", verified: true, candidates: 620, jobs: 72, glyph: { bg: "#000000", fg: "#fff", label: "Ex" } },
  { name: "Python", cat: "backend", desc: "High-level programming language.", level: "Beginner", verified: true, candidates: 2300, jobs: 205, glyph: { bg: "#3776AB", fg: "#FFD43B", label: "Py" } },
  { name: "Django", cat: "backend", desc: "Batteries-included Python web framework.", level: "Intermediate", verified: true, candidates: 612, jobs: 84, glyph: { bg: "#092E20", fg: "#fff", label: "Dj" } },
  { name: "Flask", cat: "backend", desc: "Lightweight Python micro-framework.", level: "Intermediate", verified: true, candidates: 458, jobs: 51, glyph: { bg: "#000000", fg: "#fff", label: "Fl" } },
  { name: "Java", cat: "backend", desc: "Object-oriented enterprise language.", level: "Intermediate", verified: true, candidates: 1820, jobs: 312, glyph: { bg: "#ED8B00", fg: "#fff", label: "Jv" } },
  { name: "Spring Boot", cat: "backend", desc: "Java framework for production-ready apps.", level: "Advanced", verified: true, candidates: 1140, jobs: 218, glyph: { bg: "#6DB33F", fg: "#fff", label: "Sp" } },
  { name: "PHP", cat: "backend", desc: "Server-side scripting for the web.", level: "Intermediate", verified: true, candidates: 980, jobs: 124, glyph: { bg: "#777BB4", fg: "#fff", label: "PHP" } },
  { name: "Laravel", cat: "backend", desc: "Elegant PHP framework for modern apps.", level: "Intermediate", verified: true, candidates: 510, jobs: 62, glyph: { bg: "#FF2D20", fg: "#fff", label: "Lv" } },
  { name: "REST API Development", cat: "backend", desc: "Design and build RESTful services.", level: "Intermediate", verified: true, candidates: 1320, jobs: 184, glyph: { bg: "#0ea5e9", fg: "#fff", label: "API" } },
  { name: "GraphQL", cat: "backend", desc: "Query language for flexible APIs.", level: "Advanced", verified: true, candidates: 420, jobs: 58, glyph: { bg: "#E10098", fg: "#fff", label: "GQ" } },
  { name: "Microservices", cat: "backend", desc: "Architect distributed, independent services.", level: "Advanced", verified: false, candidates: 312, jobs: 96, glyph: { bg: "#0f172a", fg: "#fff", label: "μS" } },

  // Database
  { name: "SQL", cat: "database", desc: "Standard query language for relational data.", level: "Beginner", verified: true, candidates: 2840, jobs: 387, glyph: { bg: "#0369a1", fg: "#fff", label: "SQL" } },
  { name: "MySQL", cat: "database", desc: "Open-source relational database.", level: "Intermediate", verified: true, candidates: 1620, jobs: 198, glyph: { bg: "#00758F", fg: "#fff", label: "My" } },
  {
    name: "PostgreSQL", cat: "database",
    desc: "Advanced open-source relational database.",
    level: "Advanced", verified: true, candidates: 564, jobs: 61,
    glyph: { bg: "#336791", fg: "#fff", label: "Pg" },
  },
  { name: "MongoDB", cat: "database", desc: "Flexible, document-oriented NoSQL DB.", level: "Intermediate", verified: true, candidates: 920, jobs: 142, glyph: { bg: "#47A248", fg: "#fff", label: "Mo" } },
  { name: "Oracle Database", cat: "database", desc: "Enterprise-grade RDBMS.", level: "Advanced", verified: true, candidates: 540, jobs: 96, glyph: { bg: "#C74634", fg: "#fff", label: "Or" } },
  { name: "SQL Server", cat: "database", desc: "Microsoft's enterprise database engine.", level: "Intermediate", verified: true, candidates: 780, jobs: 124, glyph: { bg: "#CC2927", fg: "#fff", label: "MS" } },
  { name: "Redis", cat: "database", desc: "In-memory data store and cache.", level: "Intermediate", verified: true, candidates: 412, jobs: 78, glyph: { bg: "#DC382D", fg: "#fff", label: "Re" } },
  { name: "Database Design", cat: "database", desc: "Schema, normalization, and modeling.", level: "Intermediate", verified: false, candidates: 234, jobs: 47, glyph: { bg: "#1e293b", fg: "#fff", label: "DB" } },
  { name: "Query Optimization", cat: "database", desc: "Tune indexes, plans, and slow queries.", level: "Advanced", verified: true, candidates: 198, jobs: 42, glyph: { bg: "#0f766e", fg: "#fff", label: "QO" } },

  // DevOps
  { name: "Git", cat: "devops", desc: "Distributed version control.", level: "Beginner", verified: true, candidates: 3120, jobs: 432, glyph: { bg: "#F05032", fg: "#fff", label: "Git" } },
  { name: "GitHub", cat: "devops", desc: "Collaboration platform for Git repos.", level: "Beginner", verified: true, candidates: 2840, jobs: 312, glyph: { bg: "#0f172a", fg: "#fff", label: "GH" } },
  { name: "GitLab", cat: "devops", desc: "Integrated DevOps platform.", level: "Intermediate", verified: true, candidates: 820, jobs: 124, glyph: { bg: "#FC6D26", fg: "#fff", label: "GL" } },
  { name: "Docker", cat: "devops", desc: "Container platform for building applications.", level: "Intermediate", verified: true, candidates: 923, jobs: 88, glyph: { bg: "#2496ED", fg: "#fff", label: "🐳" } },
  { name: "Kubernetes", cat: "devops", desc: "Orchestrate containerized workloads.", level: "Advanced", verified: true, candidates: 612, jobs: 156, glyph: { bg: "#326CE5", fg: "#fff", label: "K8s" } },
  { name: "Jenkins", cat: "devops", desc: "Open-source CI/CD automation server.", level: "Intermediate", verified: true, candidates: 780, jobs: 134, glyph: { bg: "#D33833", fg: "#fff", label: "Je" } },
  { name: "CI/CD", cat: "devops", desc: "Continuous integration and delivery practices.", level: "Intermediate", verified: true, candidates: 920, jobs: 198, glyph: { bg: "#0ea5e9", fg: "#fff", label: "CI" } },
  { name: "AWS", cat: "devops", desc: "Cloud computing platform by Amazon.", level: "Intermediate", verified: true, candidates: 1100, jobs: 112, glyph: { bg: "#FF9900", fg: "#232F3E", label: "AWS" } },
  { name: "Azure", cat: "devops", desc: "Microsoft's cloud platform.", level: "Intermediate", verified: true, candidates: 820, jobs: 142, glyph: { bg: "#0078D4", fg: "#fff", label: "Az" } },
  { name: "Google Cloud Platform", cat: "devops", desc: "Google's enterprise cloud services.", level: "Intermediate", verified: true, candidates: 540, jobs: 96, glyph: { bg: "#4285F4", fg: "#fff", label: "GCP" } },
  { name: "Linux", cat: "devops", desc: "Open-source OS used everywhere.", level: "Intermediate", verified: true, candidates: 1820, jobs: 264, glyph: { bg: "#0f172a", fg: "#FCC624", label: "Lx" } },
  { name: "Nginx", cat: "devops", desc: "High-performance web server and proxy.", level: "Intermediate", verified: true, candidates: 612, jobs: 78, glyph: { bg: "#009639", fg: "#fff", label: "Nx" } },
  { name: "Terraform", cat: "devops", desc: "Infrastructure as code, declarative style.", level: "Advanced", verified: false, candidates: 268, jobs: 62, glyph: { bg: "#7B42BC", fg: "#fff", label: "Tf" } },

  // Mobile
  { name: "Android", cat: "mobile", desc: "Build native mobile apps for Android.", level: "Intermediate", verified: true, candidates: 920, jobs: 142, glyph: { bg: "#3DDC84", fg: "#fff", label: "An" } },
  { name: "iOS", cat: "mobile", desc: "Build native apps for iPhone and iPad.", level: "Intermediate", verified: true, candidates: 720, jobs: 124, glyph: { bg: "#000000", fg: "#fff", label: "iOS" } },
  { name: "React Native", cat: "mobile", desc: "Cross-platform mobile apps with React.", level: "Intermediate", verified: true, candidates: 540, jobs: 86, glyph: { bg: "#0f172a", fg: "#61DAFB", label: "RN" } },
  { name: "Flutter", cat: "mobile", desc: "UI toolkit for building natively compiled apps.", level: "Intermediate", verified: false, candidates: 412, jobs: 39, glyph: { bg: "#02569B", fg: "#fff", label: "Fl" } },
  { name: "Kotlin", cat: "mobile", desc: "Modern language for Android development.", level: "Intermediate", verified: true, candidates: 480, jobs: 96, glyph: { bg: "#7F52FF", fg: "#fff", label: "Kt" } },
  { name: "Swift", cat: "mobile", desc: "Apple's language for iOS, macOS, and more.", level: "Intermediate", verified: true, candidates: 386, jobs: 72, glyph: { bg: "#FA7343", fg: "#fff", label: "Sw" } },
  { name: "Mobile App Testing", cat: "mobile", desc: "Quality assurance for mobile platforms.", level: "Intermediate", verified: true, candidates: 312, jobs: 56, glyph: { bg: "#16a34a", fg: "#fff", label: "MT" } },
  { name: "Firebase", cat: "mobile", desc: "Backend-as-a-service for mobile and web.", level: "Beginner", verified: true, candidates: 624, jobs: 84, glyph: { bg: "#FFCA28", fg: "#000", label: "Fb" } },

  // Data
  { name: "Excel", cat: "data", desc: "Spreadsheets, formulas, and pivot tables.", level: "Beginner", verified: true, candidates: 4120, jobs: 512, glyph: { bg: "#217346", fg: "#fff", label: "Xl" } },
  { name: "Power BI", cat: "data", desc: "Business analytics service by Microsoft.", level: "Intermediate", verified: true, candidates: 356, jobs: 31, glyph: { bg: "#F2C811", fg: "#000", label: "PB" } },
  { name: "Tableau", cat: "data", desc: "Visual analytics platform for dashboards.", level: "Intermediate", verified: true, candidates: 480, jobs: 78, glyph: { bg: "#E97627", fg: "#fff", label: "Tb" } },
  { name: "Python for Data Analysis", cat: "data", desc: "Wrangle data with Python and Jupyter.", level: "Intermediate", verified: true, candidates: 612, jobs: 124, glyph: { bg: "#3776AB", fg: "#fff", label: "PyD" } },
  { name: "Pandas", cat: "data", desc: "DataFrame library for Python analytics.", level: "Intermediate", verified: true, candidates: 540, jobs: 96, glyph: { bg: "#130754", fg: "#fff", label: "Pd" } },
  { name: "NumPy", cat: "data", desc: "Numerical computing with N-d arrays.", level: "Intermediate", verified: true, candidates: 432, jobs: 78, glyph: { bg: "#4DABCF", fg: "#fff", label: "Np" } },
  { name: "SQL Analytics", cat: "data", desc: "Analytical queries and window functions.", level: "Intermediate", verified: true, candidates: 720, jobs: 142, glyph: { bg: "#0369a1", fg: "#fff", label: "SA" } },
  { name: "Data Visualization", cat: "data", desc: "Communicate insights through visuals.", level: "Intermediate", verified: false, candidates: 312, jobs: 56, glyph: { bg: "#7c3aed", fg: "#fff", label: "Dv" } },
  { name: "ETL Testing", cat: "data", desc: "Validate extract, transform, load pipelines.", level: "Advanced", verified: true, candidates: 218, jobs: 42, glyph: { bg: "#0f766e", fg: "#fff", label: "ET" } },

  // AI
  { name: "Machine Learning", cat: "ai", desc: "Build models that learn from data.", level: "Advanced", verified: true, candidates: 640, jobs: 167, glyph: { bg: "#0ea5e9", fg: "#fff", label: "ML" } },
  { name: "Deep Learning", cat: "ai", desc: "Neural networks and modern architectures.", level: "Advanced", verified: true, candidates: 420, jobs: 124, glyph: { bg: "#1e293b", fg: "#fff", label: "DL" } },
  { name: "NLP", cat: "ai", desc: "Natural language processing and text models.", level: "Advanced", verified: true, candidates: 312, jobs: 96, glyph: { bg: "#7c3aed", fg: "#fff", label: "NLP" } },
  { name: "Computer Vision", cat: "ai", desc: "Image and video understanding with ML.", level: "Advanced", verified: false, candidates: 198, jobs: 64, glyph: { bg: "#0f766e", fg: "#fff", label: "CV" } },
  { name: "TensorFlow", cat: "ai", desc: "Machine learning framework by Google.", level: "Advanced", verified: false, candidates: 289, jobs: 26, glyph: { bg: "#FF6F00", fg: "#fff", label: "TF" } },
  { name: "PyTorch", cat: "ai", desc: "Flexible deep learning research framework.", level: "Advanced", verified: true, candidates: 312, jobs: 78, glyph: { bg: "#EE4C2C", fg: "#fff", label: "Pt" } },
  { name: "Generative AI", cat: "ai", desc: "Build apps powered by LLMs and diffusion.", level: "Advanced", verified: true, candidates: 480, jobs: 142, glyph: { bg: "#0f172a", fg: "#fff", label: "Gen" } },
  { name: "Prompt Engineering", cat: "ai", desc: "Design prompts that get reliable results.", level: "Intermediate", verified: true, candidates: 612, jobs: 124, glyph: { bg: "#a855f7", fg: "#fff", label: "Pr" } },
  { name: "AI Testing", cat: "ai", desc: "Evaluate model quality, bias, and safety.", level: "Advanced", verified: false, candidates: 142, jobs: 38, glyph: { bg: "#16a34a", fg: "#fff", label: "AIT" } },

  // Design
  { name: "Figma", cat: "design", desc: "Collaborative interface design tool.", level: "Beginner", verified: true, candidates: 783, jobs: 74, glyph: { bg: "#0f172a", fg: "#fff", label: "Fg" } },
  { name: "Wireframing", cat: "design", desc: "Low-fidelity layouts to validate structure.", level: "Beginner", verified: true, candidates: 540, jobs: 62, glyph: { bg: "#475569", fg: "#fff", label: "Wf" } },
  { name: "Prototyping", cat: "design", desc: "Interactive flows to test ideas fast.", level: "Intermediate", verified: true, candidates: 612, jobs: 78, glyph: { bg: "#7c3aed", fg: "#fff", label: "Pt" } },
  { name: "User Research", cat: "design", desc: "Interviews, usability, and synthesis.", level: "Intermediate", verified: false, candidates: 264, jobs: 51, glyph: { bg: "#0f766e", fg: "#fff", label: "UR" } },
  { name: "Design Systems", cat: "design", desc: "Reusable tokens, components, and patterns.", level: "Advanced", verified: true, candidates: 312, jobs: 64, glyph: { bg: "#1e293b", fg: "#fff", label: "DS" } },
  { name: "UI Design", cat: "design", desc: "Visual interface composition and craft.", level: "Intermediate", verified: true, candidates: 720, jobs: 96, glyph: { bg: "#ec4899", fg: "#fff", label: "UI" } },
  { name: "UX Design", cat: "design", desc: "Flows, interactions, and product thinking.", level: "Intermediate", verified: true, candidates: 680, jobs: 102, glyph: { bg: "#0ea5e9", fg: "#fff", label: "UX" } },
  { name: "Usability Testing", cat: "design", desc: "Evaluate designs with real users.", level: "Intermediate", verified: false, candidates: 198, jobs: 32, glyph: { bg: "#16a34a", fg: "#fff", label: "Us" } },

  // PM
  { name: "Agile", cat: "pm", desc: "Iterative, value-driven delivery practices.", level: "Beginner", verified: true, candidates: 2100, jobs: 312, glyph: { bg: "#0ea5e9", fg: "#fff", label: "Ag" } },
  { name: "Scrum", cat: "pm", desc: "Time-boxed framework for product teams.", level: "Intermediate", verified: true, candidates: 1820, jobs: 264, glyph: { bg: "#1e293b", fg: "#fff", label: "Sc" } },
  { name: "Kanban", cat: "pm", desc: "Visualize flow and limit work in progress.", level: "Beginner", verified: true, candidates: 1240, jobs: 142, glyph: { bg: "#0f766e", fg: "#fff", label: "Kn" } },
  { name: "Sprint Planning", cat: "pm", desc: "Forecast and commit to sprint goals.", level: "Intermediate", verified: true, candidates: 920, jobs: 124, glyph: { bg: "#7c3aed", fg: "#fff", label: "SP" } },
  { name: "Requirement Analysis", cat: "pm", desc: "Capture and clarify product needs.", level: "Intermediate", verified: true, candidates: 720, jobs: 142, glyph: { bg: "#0369a1", fg: "#fff", label: "RA" } },
  { name: "Business Analysis", cat: "pm", desc: "Bridge business goals and delivery.", level: "Intermediate", verified: true, candidates: 540, jobs: 124, glyph: { bg: "#0f172a", fg: "#fff", label: "BA" } },
  { name: "Product Management", cat: "pm", desc: "Vision, roadmap, and prioritization.", level: "Advanced", verified: false, candidates: 312, jobs: 96, glyph: { bg: "#dc2626", fg: "#fff", label: "PM" } },
  { name: "Stakeholder Communication", cat: "pm", desc: "Align teams, partners, and execs.", level: "Intermediate", verified: false, candidates: 264, jobs: 84, glyph: { bg: "#a16207", fg: "#fff", label: "SC" } },
];

Object.assign(window, { CATEGORIES, SKILLS });
