export const COUNTRIES = [
  { code: 'IN', flag: '🇮🇳', name: 'India',           dial: '+91',  min: 10, max: 10 },
  { code: 'US', flag: '🇺🇸', name: 'United States',    dial: '+1',   min: 10, max: 10 },
  { code: 'GB', flag: '🇬🇧', name: 'United Kingdom',   dial: '+44',  min: 10, max: 11 },
  { code: 'AU', flag: '🇦🇺', name: 'Australia',        dial: '+61',  min: 9,  max: 9  },
  { code: 'AE', flag: '🇦🇪', name: 'UAE',              dial: '+971', min: 9,  max: 9  },
  { code: 'SG', flag: '🇸🇬', name: 'Singapore',        dial: '+65',  min: 8,  max: 8  },
  { code: 'DE', flag: '🇩🇪', name: 'Germany',          dial: '+49',  min: 10, max: 11 },
  { code: 'FR', flag: '🇫🇷', name: 'France',           dial: '+33',  min: 9,  max: 9  },
  { code: 'JP', flag: '🇯🇵', name: 'Japan',            dial: '+81',  min: 10, max: 11 },
  { code: 'CN', flag: '🇨🇳', name: 'China',            dial: '+86',  min: 11, max: 11 },
  { code: 'BR', flag: '🇧🇷', name: 'Brazil',           dial: '+55',  min: 10, max: 11 },
  { code: 'CA', flag: '🇨🇦', name: 'Canada',           dial: '+1',   min: 10, max: 10 },
  { code: 'NL', flag: '🇳🇱', name: 'Netherlands',      dial: '+31',  min: 9,  max: 9  },
  { code: 'IT', flag: '🇮🇹', name: 'Italy',            dial: '+39',  min: 9,  max: 10 },
  { code: 'ES', flag: '🇪🇸', name: 'Spain',            dial: '+34',  min: 9,  max: 9  },
  { code: 'PK', flag: '🇵🇰', name: 'Pakistan',         dial: '+92',  min: 10, max: 10 },
  { code: 'BD', flag: '🇧🇩', name: 'Bangladesh',       dial: '+880', min: 10, max: 10 },
  { code: 'LK', flag: '🇱🇰', name: 'Sri Lanka',        dial: '+94',  min: 9,  max: 9  },
  { code: 'NP', flag: '🇳🇵', name: 'Nepal',            dial: '+977', min: 9,  max: 10 },
  { code: 'MY', flag: '🇲🇾', name: 'Malaysia',         dial: '+60',  min: 9,  max: 10 },
  { code: 'PH', flag: '🇵🇭', name: 'Philippines',      dial: '+63',  min: 10, max: 10 },
  { code: 'ID', flag: '🇮🇩', name: 'Indonesia',        dial: '+62',  min: 9,  max: 12 },
  { code: 'TH', flag: '🇹🇭', name: 'Thailand',         dial: '+66',  min: 9,  max: 9  },
  { code: 'VN', flag: '🇻🇳', name: 'Vietnam',          dial: '+84',  min: 9,  max: 10 },
  { code: 'KR', flag: '🇰🇷', name: 'South Korea',      dial: '+82',  min: 9,  max: 10 },
  { code: 'ZA', flag: '🇿🇦', name: 'South Africa',     dial: '+27',  min: 9,  max: 9  },
  { code: 'NG', flag: '🇳🇬', name: 'Nigeria',          dial: '+234', min: 10, max: 10 },
  { code: 'KE', flag: '🇰🇪', name: 'Kenya',            dial: '+254', min: 9,  max: 9  },
  { code: 'EG', flag: '🇪🇬', name: 'Egypt',            dial: '+20',  min: 10, max: 10 },
  { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia',     dial: '+966', min: 9,  max: 9  },
  { code: 'QA', flag: '🇶🇦', name: 'Qatar',            dial: '+974', min: 8,  max: 8  },
  { code: 'KW', flag: '🇰🇼', name: 'Kuwait',           dial: '+965', min: 8,  max: 8  },
  { code: 'MX', flag: '🇲🇽', name: 'Mexico',           dial: '+52',  min: 10, max: 10 },
  { code: 'AR', flag: '🇦🇷', name: 'Argentina',        dial: '+54',  min: 10, max: 11 },
];

export const TZ_COUNTRY_MAP = {
  'Asia/Calcutta':                     'IN',
  'Asia/Kolkata':                      'IN',
  'America/New_York':                  'US',
  'America/Los_Angeles':               'US',
  'America/Chicago':                   'US',
  'America/Denver':                    'US',
  'Europe/London':                     'GB',
  'Australia/Sydney':                  'AU',
  'Australia/Melbourne':               'AU',
  'Asia/Dubai':                        'AE',
  'Asia/Singapore':                    'SG',
  'Europe/Berlin':                     'DE',
  'Europe/Paris':                      'FR',
  'Asia/Tokyo':                        'JP',
  'Asia/Shanghai':                     'CN',
  'America/Sao_Paulo':                 'BR',
  'America/Toronto':                   'CA',
  'America/Vancouver':                 'CA',
  'Asia/Karachi':                      'PK',
  'Asia/Dhaka':                        'BD',
  'Asia/Colombo':                      'LK',
  'Asia/Kathmandu':                    'NP',
  'Asia/Kuala_Lumpur':                 'MY',
  'Asia/Manila':                       'PH',
  'Asia/Jakarta':                      'ID',
  'Asia/Bangkok':                      'TH',
  'Asia/Ho_Chi_Minh':                  'VN',
  'Asia/Seoul':                        'KR',
  'Africa/Johannesburg':               'ZA',
  'Africa/Lagos':                      'NG',
  'Africa/Nairobi':                    'KE',
  'Africa/Cairo':                      'EG',
  'Asia/Riyadh':                       'SA',
  'Asia/Qatar':                        'QA',
  'Asia/Kuwait':                       'KW',
  'America/Mexico_City':               'MX',
  'America/Argentina/Buenos_Aires':    'AR',
};
